### ISSUE TITLE
Numpy Module

### ISSUE THREAD

**Issue by jorjishasan** [jorjis212/Python-for-Fun#3]
Could anyone help me ?

**Comment by xorxis** [comment]
Method integration?

**Comment by jorjishasan** [comment]
`from numpy import particles`
after that what ?

**Comment by xorxis** [comment]
> `from numpy import particles` after that what ?

use * symbol

**Comment by jorjishasan** [comment]
> > `from numpy import particles` after that what ?
> 
> use * symbol

It works ! bravo

**Comment by jorjishasan** [comment]
I am gonna close this issue.

**Comment by xorxis** [comment]
okay :) happy to help
